Tavyar/Tavyar/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls')),
    path('courses/', include('course.urls', namespace='courses')),
    path('project/', include('project.urls', namespace='project')),
]

Tavyar/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('register/', views.register, name='register'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('login/', views.user_login, name='login'),
    path('dashboard/', views.user_dashboard, name='dashboard'),
    path('logout/', views.user_logout, name='logout'),
]

Tavyar/course/urls.py
# courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
    path('', views.course_list, name='list'),
    path('<slug:slug>/', views.course_detail, name='course_detail'),  # فقط برای ریدایرکت
    path('<slug:course_slug>/<slug:lesson_slug>/', views.lesson_detail, name='lesson_detail'),
]

Tavyar/home/urls.py
from django.urls import path
from .views import index_view, rules_view, help_view, interest_view
app_name = 'home'


urlpatterns = [
    path('', index_view, name='index'),
    path('rules', rules_view, name='rules'),
    path('help', help_view, name='help'),
    path('interest', interest_view, name='interest'),
]

Tavyar/templates/partials/footer.html
{% load static %}
<section class="footer">

    <div class="box-container">



        <div class="box">
            <h3>لینک های اصلی</h3>
            <a href="{% url 'home:index' %}"> <i class="fas fa-arrow-right"></i> خانه </a>
            <a href="{% url 'courses:list' %}"> <i class="fas fa-arrow-right"></i> دوره ها </a>
            <a href="{% url 'home:index' %}#reviews"> <i class="fas fa-arrow-right"></i> مربیان </a>
            <a href="{% url 'home:index' %}#arrivals"> <i class="fas fa-arrow-right"></i> پروژه ها </a>
            <a href="{% url 'home:index' %}#blogs"> <i class="fas fa-arrow-right"></i> وبلاگ </a>
        </div>

        <div class="box">
            <h3>لینک های در دسترس</h3>
            <a href="#"> <i class="fas fa-arrow-right"></i> حساب کاربری </a>
            <a href="#"> <i class="fas fa-arrow-right"></i> آموزش های کاربر </a>
            <a href="#"> <i class="fas fa-arrow-right"></i> قوانین </a>
            <a href="#"> <i class="fas fa-arrow-right"></i> علاقه مندی ها </a>
            <a href="#"> <i class="fas fa-arrow-right"></i> دیگر سرویس ها </a>
        </div>

        <div class="box" >
            <h3>ارتباط با ما</h3>
            <a href="#"dir="ltr"> <i class="fas fa-phone"></i> +98-9157160815 </a>
            <a href="#"dir="ltr"> <i class="fas fa-envelope"></i> @tavyarco </a>
            <img src="{% static 'image/worldmap.png' %}" class="map" alt="">
        </div>

    </div>

    <div class="share">

        <a href="#" class="fab fa-instagram"></a>
        <a href="#" class="fab fa-linkedin"></a>
        <a href="#" class="fab fa-pinterest"></a>
    </div>

    <div class="credit"> Web developers:Saba Pordel && Pourya Janparvar  </div>

</section>

Tavyar/templates/partials/header.html
<header class="header">

    <div class="header-1">

        <a href="{% url 'home:index' %}" class="logo"> <i class=""></i>آموزشگاه تاویار </a>

        <form action="" class="search-form">
            <input type="search" name="" placeholder="جستجو کنید" id="search-box">
            <label for="search-box" class="fas fa-search"></label>
        </form>

        <div class="icons">
            <div id="search-btn" class="fas fa-search"></div>
            <a href="{% url 'home:interest' %}" class="fas fa-heart"></a>
            <a href="#" class="fas fa-shopping-cart"></a>
            {% if request.user.is_authenticated %}
            <a href="{% url 'accounts:dashboard' %}" class="fas fa-user"></a>
            {% else %}
            <div id="login-btn" class="fas fa-user"></div>
            {% endif %}



        </div>
    </div>
    <div class="header-2">
        <nav class="navbar">
            <a href="{% url 'home:index' %}">خانه</a>

            <div class="dropdown">
                <a href="{% url 'courses:list' %}" class="dropbtn">دوره ها</a>

<!--                <ul class="dropdown-content">-->

<!--                    <li class="has-submenu">-->
<!--                        <a href="#course1">برنامه نویسی وب 👈</a>-->

<!--                        <ul class="sub-dropdown-content">-->
<!--                            <li><a href="#front-end">Front-End (رابط کاربری)</a></li>-->
<!--                            <li><a href="#back-end">Back-End (بخش سرور)</a></li>-->
<!--                            <li><a href="#full-stack">Full-Stack (کامل)</a></li>-->
<!--                        </ul>-->
<!--                    </li>-->

<!--                    <li><a href="#course2">هوش مصنوعی</a></li>-->
<!--                    <li><a href="#course3">شبکه و امنیت</a></li>-->
<!--                </ul>-->
            </div>

            <a href="{% url 'home:index' %}#reviews">مربیان</a>
            <a href="{% url 'project:list' %}">پروژه ها</a>
            <a href="{% url 'home:index' %}#blogs">وبلاگ</a>
            <a href="{% url 'home:index' %}#TAZETARIN">تازه ترین ها </a>
            <div class="dropdown">
                  <a href="#TAZETARIN">لینک های در دسترس</a>

                <ul class="dropdown-content">





                    <li><a href="{% url 'home:interest' %}">علاقه مندی ها</a></li>
                    <li class="has-submenu">
                        <a href="#course1">دیگر سرویس ها 👈</a>

                        <ul class="sub-dropdown-content">
                            <li><a href="{% url 'home:help' %}">راهنما</a></li>
                            <li><a href="{% url 'home:rules' %}">قوانین</a></li>

                        </ul>
                    </li>

                </ul>
            </div>

        </nav>
    </div>

</header>

<!-- header section ends -->

<!-- bottom navbar  -->

<nav class="bottom-navbar">
    <a href="#home" class="fas fa-home"></a>
    <a href="#featured" class="fas fa-list"></a>
    <a href="#arrivals" class="fas fa-tags"></a>
    <a href="#reviews" class="fas fa-comments"></a>
    <a href="#blogs" class="fas fa-blog"></a>
</nav>

<!-- login form  -->

<div class="login-form-container">

    <div id="close-login-btn" class="fas fa-times"></div>

    <form action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        <h3>ورود</h3>
        <span>نام کاربری</span>
        <input type="email" name="email" class="box" placeholder="ایمیل خود را وارد کنید" id="">
        <span>رمز عبور</span>
        <input type="password" name="password" class="box" placeholder="رمز عبور خود را وارد کنید" id="">
        <div class="checkbox">
            <input type="checkbox" name="" id="remember-me">
            <label for="remember-me"> به خاطر سپردن</label>
        </div>
        <input type="submit" value="ورود به حساب کاربری" class="btn">
        <p>رمز خود را فراموش کرده اید ؟ <a href="#">اینجا کلیک کنید</a></p>
        <p>ثبت نام نکرده اید ؟ <a href="{% url 'accounts:register' %}">ساخت حساب</a></p>
    </form>

</div>